
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
# Thanks for Tkinter-Designer by Parth Jadhav for creating the background and boxes, anything else was made by me; Francis Niño Cahoy


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from tkinter import ttk as ttk
import Fun as func

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")
window.title("Beadle Assistance Program (BAP)")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    362.0,
    image=image_image_1
)


canvas.create_rectangle(
    -1.5,
    62.0,
    1280.0,
    65.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    118.0,
    1281.0,
    120.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    173.0,
    1281.0,
    175.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    228.0,
    1281.0,
    230.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    283.0,
    1281.0,
    285.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    338.0,
    1281.0,
    340.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    393.0,
    1281.0,
    395.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    448.0,
    1281.0,
    450.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    503.0,
    1281.0,
    505.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    558.0,
    1281.0,
    560.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    613.0,
    1281.0,
    615.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    668.0,
    1281.0,
    670.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    723.0,
    1281.0,
    725.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    280.0,
    64.0,
    282.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    404.0,
    64.0,
    406.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    466.0,
    64.0,
    468.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    528.0,
    64.0,
    530.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    590.0,
    64.0,
    592.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    652.0,
    64.0,
    654.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    714.0,
    64.0,
    716.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    838.0,
    64.0,
    840.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    900.0,
    64.0,
    902.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    962.0,
    64.0,
    964.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1024.0,
    64.0,
    1026.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1086.0,
    64.0,
    1088.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1148.0,
    64.0,
    1150.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1210.0,
    64.0,
    1212.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1272.0,
    64.0,
    1274.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    776.0,
    64.0,
    778.0,
    720.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    342.0,
    64.0,
    344.0,
    720.0,
    fill="#000000",
    outline="")

####################################################################

name = StringVar()


def submit(klass,x,y):

    newname = name.get()
    name.set("")
    print("The name is : " + newname)
    
    klass.add_name(newname)
    canvas.create_text(x, y, text=klass.name, font="sans 18", fill="black", justify="left", anchor="w")
    
def NameGet(klass,x,y):
    
    top = Toplevel()
    top.title("get username")
    top.geometry("300x100")
    
    
    def exit():
        top.destroy()
        top.update()
    
    name_label = ttk.Label(top, text = 'name', font=('calibre',10, 'bold'))
    name_entry = ttk.Entry(top,textvariable = name, font=('calibre',10,'normal'))
    sub_btn=ttk.Button(top,text = 'Submit', command = lambda:[submit(klass,x,y), exit()])
    name_label.grid(row=0,column=0)
    name_entry.grid(row=0,column=1)
    sub_btn.grid(row=2,column=1)    

###################

datestart = IntVar()
dateend = IntVar()

def dateget():
    
    getdate = Toplevel()
    getdate.title("get date")
    getdate.grab_set()

    def exit():
        getdate.destroy()
        getdate.update()
        
    
    date_start_label = ttk.Label(getdate, text = 'date start', font=('calibre',10, 'bold'))
    date_start_entry = ttk.Entry(getdate,textvariable = datestart, font=('calibre',10,'normal'))
    
    date_end_label = ttk.Label(getdate, text = 'date end', font=('calibre',10, 'bold'))
    date_end_entry = ttk.Entry(getdate,textvariable = dateend, font=('calibre',10,'normal'))
    
    sub_btn=ttk.Button(getdate,text = 'Submit', command = lambda:[submitdate(datestart,dateend), exit()])
    
    date_start_label.grid(row=0,column=0)
    date_start_entry.grid(row=0,column=1)
    date_end_label.grid(row=1,column=0)
    date_end_entry.grid(row=1,column=1)
    
    sub_btn.grid(row=2,column=1)



def submitdate(datestart, dateend):
    try: 
        newdatestart = datestart.get()
        newdateend = dateend.get()
    except:
        error = Toplevel()
        error.title("Dumbass")
        error.geometry("200x100")
        error = ttk.Label(error, text = '''use only numbers and fill
up both sides.''', font=('calibre',10, 'bold'))
        error.grid(row=0, column=0)
        
    
    if newdatestart == 0:
        newdatestart = 1
    
    if newdatestart > newdateend:
        newdatestart += 1
    else:
        newdateend += 1
        
    increase_factor = 0
    for x in range(newdatestart, newdateend):
        func.dates_between.append(x)
        y = 91
        width_factor = 61
        width = 310 + increase_factor * width_factor
        increase_factor = increase_factor + 1
        
        canvas.create_text(width, y, text=x, font="sans 18", fill="black", justify="left", anchor="w")
        
        
        if len(func.dates_between) == 16:
            break
        else:
            continue
    
    if len(func.dates_between) < 16:
        for x in range(1, 17 - len(func.dates_between)):
            func.dates_between.append(" ")

canvas.create_text(1075, 40, text="export", font="sans 12", fill="black", justify="left", anchor="w")
export_button = Button(window, height=1, width=2, command= lambda:func.export())
export_button.place(x = 1125, y= 25)

canvas.create_text(1175, 40, text="select dates", font="sans 12", fill="black", justify="left", anchor="w")
debug_button = Button(window, height=1, width=2, command= lambda:dateget())
debug_button.place(x = 1250, y= 25)

############################################################################
    
dateget()   

canvas.create_text(50, 95, text="Name", font="sans 18", fill="black", justify="left", anchor="w")
                            
n0 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserOne,35,148)) 
n0.place (x = 5, y = 133.5)

n1 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserTwo,35,205)) 
n1.place (x = 5, y = 190)

n2 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserThree,35,259)) 
n2.place (x = 5, y = 244)

n3 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserFour,35,314)) 
n3.place (x = 5, y = 299)

n4 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserFive,35,369)) 
n4.place (x = 5, y = 354)

n5 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserSix,35,424)) 
n5.place (x = 5, y = 409)

n6 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserSeven,35,479)) 
n6.place (x = 5, y = 464)

n7 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserEight,35,534)) 
n7.place (x = 5, y = 519)

n8 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserNine,35,589)) 
n8.place (x = 5, y = 574)

n9 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserTen,35,644)) 
n9.place (x = 5, y = 629)

n10 = Button(window, height=1 , width=2 , command= lambda: NameGet(func.UserEleven,35,699)) 
n10.place (x = 5, y = 684)



#First row
w01 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserOne, w01)) 
w01.place (x = 300, y = 133.5)  #button position [0 0]

w02 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserOne, w02))
w02.place (x = 362, y = 133.5)  #button position [0 1]

w03 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserOne, w03))  
w03.place (x = 424, y = 133.5)  #button position [0 2]

w04 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserOne, w04)) 
w04.place (x = 486, y = 133.5)  #button position [0 3]

w05 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserOne, w05)) 
w05.place (x = 548, y = 133.5)  #button position [0 4]

w06 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserOne, w06)) 
w06.place (x = 610, y = 133.5)  #button position [0 5]

w07 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserOne, w07)) 
w07.place (x = 672, y = 133.5)  #button position [0 6]

w08 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserOne, w08))
w08.place (x = 734, y = 133.5)  #button position [0 7]

w09 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserOne, w09)) 
w09.place (x = 796, y = 133.5)  #button position [0 8]

w010 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserOne, w010)) 
w010.place (x = 858, y = 133.5)  #button position [0 9]

w011 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserOne, w011)) 
w011.place (x = 920, y = 133.5)  #button position [0 10]

w012 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserOne, w012)) 
w012.place (x = 982, y = 133.5)  #button position [0 11]

w013 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserOne, w013)) 
w013.place (x = 1044, y = 133.5) #button position [0 12]

w014 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserOne, w014)) 
w014.place (x = 1106, y = 133.5) #button position [0 13]

w015 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserOne, w015)) 
w015.place (x = 1168, y = 133.5) #button position [0 14]

w016 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserOne, w016)) 
w016.place (x = 1230, y = 133.5) #button position [0 15]
#first row end

#second row
w10 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserTwo, w10)) 
w10.place (x = 300, y = 190)   #button position [1 0]

w11 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserTwo, w11))
w11.place (x = 362, y = 190)  #button position [1 1]

w12 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserTwo, w12))  
w12.place (x = 424, y = 190)  #button position [1 2]

w13 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserTwo, w13)) 
w13.place (x = 486, y = 190)  #button position [1 3]

w14 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserTwo, w14)) 
w14.place (x = 548, y = 190)  #button position [1 4]

w15 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserTwo, w15)) 
w15.place (x = 610, y = 190)  #button position [1 5]

w16 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserTwo, w16)) 
w16.place (x = 672, y = 190)  #button position [1 6]

w17 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserTwo, w17))
w17.place (x = 734, y = 190)  #button position [1 7]

w18 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserTwo, w18)) 
w18.place (x = 796, y = 190)  #button position [1 8]

w19 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserTwo, w19)) 
w19.place (x = 858, y = 190)  #button position [1 9]

w110 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserTwo, w110)) 
w110.place (x = 920, y = 190)  #button position [1 10]

w111 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserTwo, w111)) 
w111.place (x = 982, y = 190)  #button position [1 11]

w112 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserTwo, w112)) 
w112.place (x = 1044, y = 190) #button position [1 12]

w113 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserTwo, w113)) 
w113.place (x = 1106, y = 190) #button position [1 13]

w114 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserTwo, w114)) 
w114.place (x = 1168, y = 190) #button position [1 14]

w115 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserTwo, w115)) 
w115.place (x = 1230, y = 190) #button position [1 15]
#second row end

#third row
w20 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserThree, w20)) 
w20.place (x = 300, y = 244)   #button position [2 0]

w21 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserThree, w21))
w21.place (x = 362, y = 244)  #button position [2 1]

w22 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserThree, w22))  
w22.place (x = 424, y = 244)  #button position [2 2]

w23 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserThree, w23)) 
w23.place (x = 486, y = 244)  #button position [2 3]

w24 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserThree, w24)) 
w24.place (x = 548, y = 244)  #button position [2 4]

w25 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserThree, w25)) 
w25.place (x = 610, y = 244)  #button position [2 5]

w26 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserThree, w26)) 
w26.place (x = 672, y = 244)  #button position [2 6]

w27 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserThree, w27))
w27.place (x = 734, y = 244)  #button position [2 7]

w28 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserThree, w28)) 
w28.place (x = 796, y = 244)  #button position [2 8]

w29 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserThree, w29)) 
w29.place (x = 858, y = 244)  #button position [2 9]

w210 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserThree, w210)) 
w210.place (x = 920, y = 244)  #button position [2 10]

w211 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserThree, w211)) 
w211.place (x = 982, y = 244)  #button position [22 11]

w212 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserThree, w212)) 
w212.place (x = 1044, y = 244) #button position [2 12]

w213 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserThree, w213)) 
w213.place (x = 1106, y = 244) #button position [2 13]

w214 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserThree, w214)) 
w214.place (x = 1168, y = 244) #button position [2 14]

w215 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserThree, w215)) 
w215.place (x = 1230, y = 244) #button position [2 15]
#third row end

#fourth row
w30 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserFour, w30)) 
w30.place (x = 300, y = 299)   #button position [3 0]

w31 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserFour, w31))
w31.place (x = 362, y = 299)  #button position [3 1]

w32 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserFour, w32))  
w32.place (x = 424, y = 299)  #button position [3 2]

w33 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserFour, w33)) 
w33.place (x = 486, y = 299)  #button position [3 3]

w34 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserFour, w34)) 
w34.place (x = 548, y = 299)  #button position [3 4]

w35 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserFour, w35)) 
w35.place (x = 610, y = 299)  #button position [3 5]

w36 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserFour, w36)) 
w36.place (x = 672, y = 299)  #button position [3 6]

w37 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserFour, w37))
w37.place (x = 734, y = 299)  #button position [3 7]

w38 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserFour, w38)) 
w38.place (x = 796, y = 299)  #button position [3 8]

w39 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserFour, w39)) 
w39.place (x = 858, y = 299)  #button position [3 9]

w310 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserFour, w310)) 
w310.place (x = 920, y = 299)  #button position [3 10]

w311 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserFour, w311)) 
w311.place (x = 982, y = 299)  #button position [0 11]

w312 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserFour, w312)) 
w312.place (x = 1044, y = 299) #button position [3 12]

w313 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserFour, w313)) 
w313.place (x = 1106, y = 299) #button position [3 13]

w314 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserFour, w314)) 
w314.place (x = 1168, y = 299) #button position [3 14]

w315 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserFour, w315)) 
w315.place (x = 1230, y = 299) #button position [3 15]
#fourth row end

#fifth row
w40 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserFive, w40)) 
w40.place (x = 300, y = 354)  #button position [4 0]

w41 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserFive, w41))
w41.place (x = 362, y = 354)  #button position [4 1]

w42 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserFive, w42))  
w42.place (x = 424, y = 354)  #button position [4 2]

w43 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserFive, w43)) 
w43.place (x = 486, y = 354)  #button position [4 3]

w44 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserFive, w44)) 
w44.place (x = 548, y = 354)  #button position [4 4]

w45 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserFive, w45)) 
w45.place (x = 610, y = 354)  #button position [4 5]

w46 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserFive, w46)) 
w46.place (x = 672, y = 354)  #button position [4 6]

w47 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserFive, w47))
w47.place (x = 734, y = 354)  #button position [4 7]

w48 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserFive, w48)) 
w48.place (x = 796, y = 354)  #button position [4 8]

w49 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserFive, w49)) 
w49.place (x = 858, y = 354)  #button position [4 9]

w410 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserFive, w410)) 
w410.place (x = 920, y = 354)  #button position [4 10]

w411 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserFive, w411)) 
w411.place (x = 982, y = 354)  #button position [4 11]

w412 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserFive, w412)) 
w412.place (x = 1044, y = 354) #button position [4 12]

w413 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserFive, w413)) 
w413.place (x = 1106, y = 354) #button position [4 13]

w414 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserFive, w414)) 
w414.place (x = 1168, y = 354) #button position [4 14]

w415 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserFive, w415)) 
w415.place (x = 1230, y = 354) #button position [4 15]
#fifth row end

#sixth row
w50 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserSix, w50)) 
w50.place (x = 300, y = 409)   #button position [5 0]

w51 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserSix, w51))
w51.place (x = 362, y = 409)  #button position [5 1]

w52 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserSix, w52))  
w52.place (x = 424, y = 409)  #button position [5 2]

w53 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserSix, w53)) 
w53.place (x = 486, y = 409)  #button position [5 3]

w54 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserSix, w54)) 
w54.place (x = 548, y = 409)  #button position [5 4]

w55 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserSix, w55)) 
w55.place (x = 610, y = 409)  #button position [5 5]

w56 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserSix, w56)) 
w56.place (x = 672, y = 409)  #button position [5 6]

w57 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserSix, w57))
w57.place (x = 734, y = 409)  #button position [5 7]

w58 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserSix, w58)) 
w58.place (x = 796, y = 409)  #button position [5 8]

w59 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserSix, w59)) 
w59.place (x = 858, y = 409)  #button position [5 9]

w510 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserSix, w510)) 
w510.place (x = 920, y = 409)  #button position [5 10]

w511 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserSix, w511)) 
w511.place (x = 982, y = 409)  #button position [5 11]

w512 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserSix, w512)) 
w512.place (x = 1044, y = 409) #button position [5 12]

w513 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserSix, w513)) 
w513.place (x = 1106, y = 409) #button position [5 13]

w514 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserSix, w514)) 
w514.place (x = 1168, y = 409) #button position [5 14]

w515 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserSix, w515)) 
w515.place (x = 1230, y = 409) #button position [5 15]
#sixth row end

#seventh row
w60 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserSeven, w60)) 
w60.place (x = 300, y = 464)   #button position [6 0]

w61 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserSeven, w61))
w61.place (x = 362, y = 464)  #button position [6 1]

w62 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserSeven, w62))  
w62.place (x = 424, y = 464)  #button position [6 2]

w63 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserSeven, w63)) 
w63.place (x = 486, y = 464)  #button position [6 3]

w64 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserSeven, w64)) 
w64.place (x = 548, y = 464)  #button position [6 4]

w65  = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserSeven, w65)) 
w65.place (x = 610, y = 464)  #button position [6 5]

w66 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserSeven, w66)) 
w66.place (x = 672, y = 464)  #button position [6 6]

w67 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserSeven, w67))
w67.place (x = 734, y = 464)  #button position [6 7]

w68 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserSeven, w68)) 
w68.place (x = 796, y = 464)  #button position [6 8]

w69 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserSeven, w69)) 
w69.place (x = 858, y = 464)  #button position [6 9]

w610 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserSeven, w610)) 
w610.place (x = 920, y = 464)  #button position [6 10]

w611 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserSeven, w611)) 
w611.place (x = 982, y = 464)  #button position [6 11]

w612 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserSeven, w612)) 
w612.place (x = 1044, y = 464) #button position [6 12]

w613 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserSeven, w613)) 
w613.place (x = 1106, y = 464) #button position [6 13]

w614 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserSeven, w614)) 
w614.place (x = 1168, y = 464) #button position [6 14]

w615  = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserSeven, w615)) 
w615.place (x = 1230, y = 464) #button position [6 15]
#seventh row end

#eigth row
w70 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserEight, w70)) 
w70.place (x = 300, y = 519)   #button position [7 0]

w71 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserEight, w71))
w71.place (x = 362, y = 519)  #button position [7 1]

w72 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserEight, w72))  
w72.place (x = 424, y = 519)  #button position [7 2]

w73 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserEight, w73)) 
w73.place (x = 486, y = 519)  #button position [7 3]

w74 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserEight, w74)) 
w74.place (x = 548, y = 519)  #button position [7 4]

w75 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserEight, w75)) 
w75.place (x = 610, y = 519)  #button position [7 5]

w76 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserEight, w76)) 
w76.place (x = 672, y = 519)  #button position [7 6]

w77 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserEight, w77))
w77.place (x = 734, y = 519)  #button position [7 7]

w78 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserEight, w78)) 
w78.place (x = 796, y = 519)  #button position [7 8]

w79 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserEight, w79)) 
w79.place (x = 858, y = 519)  #button position [7 9]

w710 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserEight, w710)) 
w710.place (x = 920, y = 519)  #button position [7 10]

w711 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserEight, w711)) 
w711.place (x = 982, y = 519)  #button position [7 11]

w712 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserEight, w712)) 
w712.place (x = 1044, y = 519) #button position [7 12]

w713 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserEight, w713)) 
w713.place (x = 1106, y = 519) #button position [7 13]

w714 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserEight, w714)) 
w714.place (x = 1168, y = 519) #button position [7 14]

w715 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserEight, w715)) 
w715.place (x = 1230, y = 519) #button position [7 15]
#eigth row end

#ninth row
w80 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserNine, w80)) 
w80.place (x = 300, y = 574)   #button position [8 0]

w81 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserNine, w81))
w81.place (x = 362, y = 574)  #button position [8 1]

w82 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserNine, w82))  
w82.place (x = 424, y = 574)  #button position [8 2]

w83 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserNine, w83)) 
w83.place (x = 486, y = 574)  #button position [8 3]

w84 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserNine, w84)) 
w84.place (x = 548, y = 574)  #button position [8 4]

w85 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserNine, w85)) 
w85.place (x = 610, y = 574)  #button position [8 5]

w86 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserNine, w86)) 
w86.place (x = 672, y = 574)  #button position [8 6]

w87 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserNine, w87))
w87.place (x = 734, y = 574)  #button position [8 7]

w88 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserNine, w88)) 
w88.place (x = 796, y = 574)  #button position [8 8]

w89 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserNine, w89)) 
w89.place (x = 858, y = 574)  #button position [8 9]

w810 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserNine, w810)) 
w810.place (x = 920, y = 574)  #button position [8 10]

w811 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserNine, w811)) 
w811.place (x = 982, y = 574)  #button position [8 11]

w812 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserNine, w812)) 
w812.place (x = 1044, y = 574) #button position [8 12]

w813 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserNine, w813)) 
w813.place (x = 1106, y = 574) #button position [8 13]

w814 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserNine, w814)) 
w814.place (x = 1168, y = 574) #button position [8 14]

w815 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserNine, w815)) 
w815.place (x = 1230, y = 574) #button position [8 15]
#ninth row end

#tenth row 
w90 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserTen, w90)) 
w90.place (x = 300, y = 629)   #button position [9 0]

w91 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserTen, w91))
w91.place (x = 362, y = 629)  #button position [9 1]

w92 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserTen, w92))  
w92.place (x = 424, y = 629)  #button position [9 2]

w93 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserTen, w93)) 
w93.place (x = 486, y = 629)  #button position [9 3]

w94 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserTen, w94)) 
w94.place (x = 548, y = 629)  #button position [9 4]

w95 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserTen, w95)) 
w95.place (x = 610, y = 629)  #button position [9 5]

w96 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserTen, w96)) 
w96.place (x = 672, y = 629)  #button position [9 6]

w97 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserTen, w97))
w97.place (x = 734, y = 629)  #button position [9 7]

w98 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserTen, w98)) 
w98.place (x = 796, y = 629)  #button position [9 8]

w99 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserTen, w99)) 
w99.place (x = 858, y = 629)  #button position [9 9]

w910 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserTen, w910)) 
w910.place (x = 920, y = 629)  #button position [9 10]

w911 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserTen, w911)) 
w911.place (x = 982, y = 629)  #button position [9 11]

w912 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserTen, w912)) 
w912.place (x = 1044, y = 629) #button position [9 12]

w913 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserTen, w913)) 
w913.place (x = 1106, y = 629) #button position [9 13]

w914 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserTen, w914)) 
w914.place (x = 1168, y = 629) #button position [9 14]

w915 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserTen, w915)) 
w915.place (x = 1230, y = 629) #button position [9 15]
#tenth row end

#leven row
w100 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[0], func.UserEleven, w100)) 
w100.place (x = 300, y = 684)   #button position [1 0]

w101 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[1], func.UserEleven, w101))
w101.place (x = 362, y = 684)  #button position [10 1]

w102 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[2], func.UserEleven, w102))  
w102.place (x = 424, y = 684)  #button position [10 2]

w103 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[3], func.UserEleven, w103)) 
w103.place (x = 486, y = 684)  #button position [10 3]

w104 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[4], func.UserEleven, w104)) 
w104.place (x = 548, y = 684)  #button position [10 4]

w105 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[5], func.UserEleven, w105)) 
w105.place (x = 610, y = 684)  #button position [10 5]

w106 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[6], func.UserEleven, w106)) 
w106.place (x = 672, y = 684)  #button position [10 6]

w107 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[7], func.UserEleven, w107))
w107.place (x = 734, y = 684)  #button position [10 7]

w108 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[8], func.UserEleven, w108)) 
w108.place (x = 796, y = 684)  #button position [10 8]

w109 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[9], func.UserEleven, w109)) 
w109.place (x = 858, y = 684)  #button position [10 9]

w1010 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[10], func.UserEleven, w1010)) 
w1010.place (x = 920, y = 684)  #button position [10 10]

w1011 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[11], func.UserEleven, w1011)) 
w1011.place (x = 982, y = 684)  #button position [10 11]

w1012 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[12], func.UserEleven, w1012)) 
w1012.place (x = 1044, y = 684) #button position [10 12]

w1013 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[13], func.UserEleven, w1013)) 
w1013.place (x = 1106, y = 684) #button position [10 13]

w1014 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[14], func.UserEleven, w1014)) 
w1014.place (x = 1168, y = 684) #button position [10 14]

w1015 = Button(window, height=1 , width=2 , command= lambda: func.add(func.dates_between[15], func.UserEleven, w1015)) 
w1015.place (x = 1230, y = 684) #button position [10 15]
#leventh row end


"""class ButtonSpecial:
    def __init__(self, date, posx, posy):
        self.date = date
        self.posx = posx
        self.posy = posy

    def summon(self):
        butt = Button(window, height=1, width=2, command=up1)
        butt.place(self.posx,self.posy)
    
def up1(date):  
    User.Dates
    for x in """
    


window.resizable(False, False)
window.mainloop()
